### ISSUE TITLE
Theorem for ¬(p ↔ ¬p) missing?

### ISSUE THREAD

**Issue by MatteoGaetzner** [leanprover/theorem_proving_in_lean4#104]
Dear lean4 maintainers,

Thanks for your work, I love playing with lean4. 
Unfortunately I got stuck with proving one of the exercise theorems in _Propositions and Proofs_ ,¬(p ↔ ¬p), and couldn't find a proof in the source code either. Most likely I'm looking at the wrong place or just can't recognize it because.
I'd appreciate any help.

Cheers,
Matteo

**Comment by MatteoGaetzner** [comment]
Hey timotree3, thanks for the pointer to the community chat and the solution! Will ask in the community chat next time I have a similar question.

I was thinking about adding a `solution.lean` file (or a file for each chapter) to this repository. I think many people use this resource kind of like a textbook and use the exercises for practice. Many likely get stuck like me and look in this repo for solutions. If we would solutions here, they could get unstuck faster.

An alternative to this could also be to provide a disclaimer somewhere in the document that they could ask for solutions in the community chat. However, this could lead to someone having to answer the same question over and over again. 

What do you think? I could add solutions for the first four chapters if wanted.

**Comment by timotree3** [comment]
Both ideas (solutions or Zulip pointer) seem reasonable to me! I don't know if there's a reason that solutions haven't already been included, so it might be worth proposing to a wider audience. Maybe make a thread in the Zulip on the topic of adding solutions to TPIL?

**Comment by MatteoGaetzner** [comment]
Sounds good, will do 👍
