### ISSUE TITLE
Hypotheses as variables not available in theorems with lean 4.12

### ISSUE THREAD

**Issue by ketilwright** [leanprover/theorem_proving_in_lean4#130]
After updating from lean 4.8 to 4.12, I found it necessary to change some of the examples in Chapter 4 (Quantifiers and Equality)

There are many problems reported here:

variable (a b c d e : Nat)
variable (h1 : a = b)
variable (h2 : b = c + 1)
variable (h3 : c = d)
variable (h4 : e = 1 + d)

theorem T 
   : a = e :=
  calc
    a = b      := h1
    _ = c + 1  := h2
    _ = d + 1  := congrArg Nat.succ h3
    _ = 1 + d  := Nat.add_comm d 1
    _ = e      := Eq.symm h4

I found that I can move the variable statements into the theorem to fix this.

theorem T 
  (a b c d e : Nat)
  (h1 : a = b)
  (h2 : b = c + 1)
  (h3 : c = d)
  (h4 : e = 1 + d)
    : a = e :=
  calc
    a = b      := h1
    _ = c + 1  := h2
    _ = d + 1  := congrArg Nat.succ h3
    _ = 1 + d  := Nat.add_comm d 1
    _ = e      := Eq.symm h4

**Comment by ketilwright** [comment]
Another example is in the following chapter:

```
variable (g : Nat → Nat → Nat)
variable (hg : g 0 0 = 0)

theorem gex1 : ∃ x, g x x = x := ⟨0, hg⟩
theorem gex2 : ∃ x, g x 0 = x := ⟨0, hg⟩
theorem gex3 : ∃ x, g 0 0 = x := ⟨0, hg⟩
theorem gex4 : ∃ x, g x x = 0 := ⟨0, hg⟩


```

I find I must do something similar to my previous post:

```
variable (g : Nat → Nat → Nat)
--variable (hg : g 0 0 = 0)


theorem gex1 (hg : g 0 0 = 0) : ∃ x, g x x = x := ⟨0, hg⟩
theorem gex2 (hg : g 0 0 = 0) : ∃ x, g x 0 = x := ⟨0, hg⟩
theorem gex3 (hg : g 0 0 = 0) : ∃ x, g 0 0 = x := ⟨0, hg⟩
theorem gex4 (hg : g 0 0 = 0) : ∃ x, g x x = 0 := ⟨0, hg⟩

```

**Comment by obokaman** [comment]
Why was this issue closed? I had the same issue when trying to execute some of the examples of Chapter 4. I was going to file a bug when I found this issue.

**Comment by ketilwright** [comment]
I suppose I closed it once I understood this particular problem. 

I suspect this is just an example of a more general problem with TPIL, which doesn't appear to have been maintained in sync with the rest of lean4. Consequently, here we have one case (of many), where examples & exercises in TPIL don't work without some modification.

I will re-open it.
