### ISSUE TITLE
"Try it!" links

### ISSUE THREAD

**Issue by digama0** [leanprover/theorem_proving_in_lean4#30]
https://leanprover.github.io/theorem_proving_in_lean4/introduction.html has the text:

> If you are reading the book online, you will see a button that reads "try it!" Pressing the button opens up a tab with a Lean editor, and copies the example with enough surrounding context to make the code compile correctly. You can type things into the editor and modify the examples, and Lean will check the results and provide feedback continuously as you type. We recommend running the examples and experimenting with the code on your own as you work through the chapters that follow.

There is no "try it" button however, this is old text from TPIL. Not sure whether the text should be edited or the "try it" links should be added, though.

**Comment by leodemoura** [comment]
Yes, we want the "try it" button :)
BTW, it already works inside of VS Code, Thanks to @lovettchris. You can open the documentation inside of VS Code, using the command "Lean 4: Open Documentation View", and the "try it" button copies the examples to our buffer.

**Comment by digama0** [comment]
Maybe this should be mentioned in the introduction? I know that Jeremy was somewhat dissatisfied with the try it links compared to a parallel text containing all the examples from a given chapter, which is what he is doing in [MIL](https://github.com/avigad/mathematics_in_lean), so perhaps we should point people toward reading the documentation from VS Code.

**Comment by lovettchris** [comment]
Yep, you can even use the TryIt button on an untitled Lean4 file like this so it's very easy to setup:

https://user-images.githubusercontent.com/18707114/157804744-2a8fd4cd-dd60-4ddb-8107-71d284f7fcfe.mp4

**Comment by leodemoura** [comment]
@digama0 I update the introduction and added a link to the Quickstart instructions @lovettchris wrote.

**Comment by digama0** [comment]
Thanks!

**Comment by ziyuang** [comment]
> Yep, you can even use the TryIt button on an untitled Lean4 file like this so it's very easy to setup:
> 
>  QuickTryIt.mp4

I cannot see the command "Lean 4: Open Documentation View" at 0:06:
![Screenshot 2024-10-14 130658](https://github.com/user-attachments/assets/b3c3c15e-9d5b-4a47-b1a0-6b9b0d130501)

but only the InfoView panel. Any ideas on what I am missing?
