### ISSUE TITLE
Dependent cartesian product example

### ISSUE THREAD

**Issue by palutz** [leanprover/theorem_proving_in_lean4#34]
In the dependent cartesian product example, there is:
```lean
universe u v

def f (α : Type u) (β : α → Type v) (a : α) (b : β a) : (a : α) × β a :=
  ⟨a, b⟩
```

If I rewrite it as: 
```lean
variable (α : Type u)
variable (β : α → Type v)
def f (a : α)(b: β a) : (a : α) × (b : β a) := ⟨a, b⟩
````
I got an error on the b type, but I don't understand why and the message is pretty cryptic: 

> type mismatch
>   b
> has type
>   β a : Type v
> but is expected to have type
>   β a : Type v

Anyone can help me out here, please?

**Comment by Kha** [comment]
Hi, the best place for asking questions about Lean is the Lean Zulip at https://leanprover.zulipchat.com/.

**Comment by palutz** [comment]
That was one of the fastest answers I ever got on Github.
Thanks
